# Generated by Django 4.2.1 on 2023-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bot_id", models.BigIntegerField()),
                ("type", models.CharField(max_length=16)),
                ("serialized_chat", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("chat_id", models.BigIntegerField()),
                ("bot_id", models.BigIntegerField()),
                ("message_thread_id", models.BigIntegerField(default=None, null=True)),
                ("from_peer", models.BigIntegerField(default=None, null=True)),
                ("from_chat", models.BigIntegerField(default=None, null=True)),
                ("serialized_message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("serialized_user", models.TextField()),
            ],
        ),
    ]
