# Generated by Django 4.2.1 on 2023-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                ("bot_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=1024)),
                ("allowed_updates", models.TextField()),
                ("secret_token", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
