# Generated by Django 4.2.1 on 2023-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0002_webhook_user_first_name_user_last_name_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
