# Generated by Django 4.2.1 on 2023-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0003_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("chat_id", models.BigIntegerField()),
                ("bot_id", models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="message",
            name="from_chat",
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to_message_id",
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
