# Generated by Django 4.2.1 on 2023-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0005_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="id",
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("message_id", "bot_id"), name="unique_message_bot"
            ),
        ),
    ]
