# Generated by Django 4.2.1 on 2023-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0006_message_id_alter_message_message_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSession",
            fields=[
                ("bot_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("session_string", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
